### ISSUE TITLE
[question] Computation of cohen.d(..., paired = TRUE)

### ISSUE THREAD

**Issue by pipomas** [mtorchiano/effsize#14]
I just used your cohen.d function with the argument paired = TRUE, since I want to compute the effect size of two means from a repeated measures design. In the help file of the function, it is not stated how the function calculates d when paired = TRUE. Are you using the method reported in  [Morris and DeShon (2002; see equation 8)](http://psych.colorado.edu/~willcutt/pdfs/morris_2002.pdf)?

**Comment by mtorchiano** [comment]
Actually the function uses the method by Gibbons  et al. that is reported in equation 4 of the paper that you cited.
