### ISSUE TITLE
Standard Deviation of cohen's d

### ISSUE THREAD

**Issue by tkerwin** [mtorchiano/effsize#19]
You have 
`S_d = sqrt(((n1+n2)/(n1*n2) + .5*dd^2/df) * ((n1+n2)/df))`

and reference The Handbook of Research Synthesis and Meta-Analysis (2009) p 238.  However, on the copy of the book I viewed online (through Project Muse), p 238 doesn't have any information on this, but p 226 gives the variance of d as:

`v_d = (n1 + n2)/(n1*n2) + d^2/(2*(n1+n2))`

Where does the extra term of ((n1+n2)/df) come from?

**Comment by mtorchiano** [comment]
I tried to reconstruct the source of the formula but I couldn't.
Therefore I decided to fall back the to the standard

Robert J. Grissom and John J. Kim (2005)
Effect size for researchers
Lawrence Erlbaum Associates
Equation 3.13 page 60
