### ISSUE TITLE
Direction

### ISSUE THREAD

**Issue by Bernardsj** [mtorchiano/effsize#24]
When using cohen.d(), the factor level order no longer allows you to dictate which group set comes first. This causes the direction of cohen's d to be off depending on the situation.

Is there any way to input what level you want as group 1 vs 2 to ensure the direction of the effect size is correct, such as in time series data?

**Comment by mtorchiano** [comment]
There was a bug in the cohen.d that ignored the order of factor levels. This ha been fixed in response to issue #27
