### ISSUE TITLE
How can you specify a specific SD in Cohen's d calculation?

### ISSUE THREAD

**Issue by earcanal** [mtorchiano/effsize#26]
My understanding is that it's sometimes desirable to specify the SD of one of the two factors (e.g. the baseline SD) when calculating Cohen's d.  This might already be possible, but it wasn't clear to me when reading the `cohen.d()` docs.

**Comment by mtorchiano** [comment]
Currently the default for computing the d is to use a pooled sd.
Anyway if you set `pooled=FALSE` the StDev of the control group (the second one) is used instead.

**Comment by earcanal** [comment]
That's clear. Is it worth adding that to the docs?

**Comment by mtorchiano** [comment]
Thanks for the suggestion, I'm going to add it to the man page. 
I just submitted a new version of the package, so the updated man page will find a place in a future release.
