### ISSUE TITLE
cohen.d not recognizing numeric values

### ISSUE THREAD

**Issue by melissagwolf** [mtorchiano/effsize#41]
cohen.d(df$X1TXMSCR~df$poverty)
Error in cohen.d.default(df$X1TXMSCR, df$poverty) : First parameter must be a numeric type

is.numeric(df$X1TXMSCR)
[1] TRUE

is.factor(df$poverty)
[1] TRUE

Edit: The issue is that effsize doesn't recognize objects of "haven_labelled" type as "numeric". 

class(df$X1TXMSCR)
[1] "haven_labelled"

When I changed the variable to numeric, it worked.

**Comment by mtorchiano** [comment]
Thanks for your issue report, the test in cohen.d was using `class()` instead of the simpler `is.numeric()` now it has changed.
