### ISSUE TITLE
Effect size is wrong for paired data

### ISSUE THREAD

**Issue by carstenschwede** [mtorchiano/effsize#49]
`rstatix::cohens_d` and `lsr::cohensD` report different effect sizes than `effsize::cohen.d` for paired data. Not related to #48 (i.e. does not improve by changing sorting order).

Working example exhibiting the issue:

```
# Paired samples effect size
df <- data.frame(
  id = 1:5,
  pre  = c(110, 122, 101, 120, 140),
  post = c(150, 160, 110, 140, 155)
)
df <- df %>% gather(key = "treatment", value = "value", -id)

set.seed(1234)
(df %>% rstatix::cohens_d(value ~ treatment, paired = T))$effsize
#1.75

lsr::cohensD(value ~ treatment,data = df,method = "paired")
#1.75

effsize::cohen.d(value ~ treatment, data=df, paired=T,hedges.correction=F)$estimate
#1.32
```

**Comment by mtorchiano** [comment]
I think the difference is in how paired data are treated.

In particular, when working with a matched study, the standard deviation within groups can be imputed from the standard deviation of the difference, as

$$ S_{within} = S_{diff} / \sqrt{2(1-r)} $$

where $r$ is the correlation between pairs of observations (e.g., the pretest-posttest
correlation).

I used formula 4.27 from:
Michael Borenstein, L. V. Hedges, J. P. T. Higgins and H. R. Rothstein, Introduction to Meta-Analysis.

If you want to get a comparable result to the one you get from the other packages you should use a single sample variation of the `cohen.d` function., e.g.:

```r
pairdiff = diff(df$value,lag=dim(df)[1]/2)
effsize::cohen.d(pairdiff,NA, data=df, paired=T,hedges.correction=F)$estimate
```
