### ISSUE TITLE
Fix cohen d for within-subjects (paired) pretest-posttest measures

### ISSUE THREAD

**Issue by mtorchiano** [mtorchiano/effsize#6]
See:
Feingold, A. (2009). Effect Sizes for Growth-Modeling Analysis for Controlled Clinical. Psychological Methods 14, 43-53. 

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2712654/

when `paired==TRUE` use the change `sd` instead of the pooled `sd`

**Comment by LadislasFr** [comment]
Hi,

I am not 100% certain of what I say below so correct me if you think I am wrong.

According to Howell (link below), it is not possible to calculate 95% confidence intervals around Cohen's d by directly subtracting and adding a constant to d (as it is the case in the effsize cohen.d function, the constant in the source code is called `Z = -qt((1 - conf.level)/2, df)`). 
It makes sense when taking account of the non-central and non-symmetrical distributions of the lower and upper distributions of the non-centrality parameter (ncp) around an observed t-value.

Knowing that, we programmed a little function that is seeking for the ncp that reduces probability at lower and upper boundaries of confidence for Cohen's d (based on a single differential variable, for instance mean after treatment - mean at baseline) using a "fsolve" function. 

For independant measures, the idea is the same but the computation of the boundaries is defined by slight difference calculation (see Howell 2010).

Let me know if you have any questions on this method.

Ladislas

https://www.uvm.edu/~dhowell/methods7/Supplements/Confidence%20Intervals%20on%20Effect%20Size.pdf

**Comment by mtorchiano** [comment]
I read the document, and added the computation in the `cohen.d` function.

**Comment by mtorchiano** [comment]
Available in version 0.6.o
