### ISSUE TITLE
`cliff.delta` formula does not use same input as `cohen.d` or `VD.A`

### ISSUE THREAD

**Issue by josesho** [mtorchiano/effsize#7]
The current implementation of `cliff.delta` does not allow one to separately specify the values and the factors, unlike in the functions for `cohen.d` and `VD.A`. From the documentation for the latter two:

> d can be a numeric vector giving either the data values (if f is a factor) or the treatment group values (if f is a numeric vector)

This is not the case for `cliff.delta`; instead one must specify 2 separate numeric vectors. 

Re-writing the `cliff.delta` function to match the syntax of the other 2 would be very helpful, especially when using [standard evaluation](https://cran.r-project.org/web/packages/dplyr/vignettes/nse.html) to programmatically select the desired effect size.

**Comment by josesho** [comment]
Pull request #8 submitted.

**Comment by mtorchiano** [comment]
Close with merge, available in versione 0.6.1
